### ISSUE TITLE
是不是忘记写了 link

### ISSUE THREAD

**Issue by zisheng-ai** [WangZiXiao-ChenDu/react-native-screenshot-observer#2]

**Comment by WangZiXiao-ChenDu** [comment]
多谢提醒

**Comment by zisheng-ai** [comment]
这是我的库：https://github.com/sishuguojixuefu/react-native-screenshot ，支持 ios，android，ios端依赖了你的这个库，谢谢作者贡献代码。能加个联系方式吗
